name: "Repository Get"
description: "Get the repository Details if they exist"

inputs:
 repo-name:
   description: "Name of the repository to attempt to get"
   required: true
 owner-name:
   description: "The repository owner"
   required: true
 pat-token:
  description: "The GitHub token to use. It must have enough privileges to make API calls"
  required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Repo Get API calls"
      id: repo_get_call
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.pat-token }}
        repo_name: ${{ inputs.repo-name }}
        owner_name: ${{ inputs.owner-name }}
      run: |
        gh API \
        "repos/$owner_name/$repo_name" \
        -H "Accept: application/vnd.github.v3+json" 
        -H "Authorization: $GH_TOKEN \
        --include \
        -X GET \
        -o repo_get_output.json
    - name: Set output  
      shell: bash
      id: set_output
      run: echo "::set-output name=repo_get_output::$(cat repo_get_output.json)"

outputs:     
  repo_get_output:
    description: "The repository details"
    value: ${{ steps.set_output.outputs.repo_get_output }}  
