name: "Repository Get"
description: "Get the repository Details if they exist"

inputs:
 repo-name:
   description: "Name of the repository to attempt to get"
   required: true
 owner-name:
   description: "The repository owner"
   required: true
 pat-token:
  description: "The GitHub token to use. It must have enough privileges to make API calls"
  required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Repo Get API calls"
      id: repo_get_call
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.pat-token }}
        repo_name: ${{ inputs.repo-name }}
        owner_name: ${{ inputs.owner-name }}
      run: |
        set +e
        gh api \
          "repos/$owner_name/$repo_name" \
          -H "Accept: application/vnd.github.v3+json" 
          -H "Authorization: $GH_TOKEN \
          --include \
          -X GET \
          -o repo_get_output.json
        if [ $? -ne 0 ]; then
          echo " API call failed, but we are continuing execution..."
          response_status=$(cat repo_get_output.json | jq -r '.status')
          echo $response_status
          echo $response_status > response_status.txt
        fi  
          
    - name: Set output  
      shell: bash
      id: set_output
      run: |
        echo "repo_get_output=$(cat repo_get_output.json) >> GITHUB_OUTPUT"
        echo "response_status=$(cat response_status.txt) >> GITHUB_ENV" 
outputs:     
  repo_get_output:
    description: "The repository details"
    value: ${{ steps.set_output.outputs.repo_get_output }} 
  response_status:
    description: "The response status"
    value: ${{ steps.set_output.outputs.response_status }} 
