name: "Repository Get"
description: "Get the repository Details if they exist"

inputs:
 repo-name:
   description: "Name of the repository to attempt to get"
   required: true
 owner-name:
   description: "The repository owner"
   required: true
 pat-token:
  description: "The GitHub token to use. It must have enough privileges to make API calls"
  required: true

runs:
  using: composite
  steps:
    - name: Repo Get API calls"
      id: repo_get_call
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.pat-token }}
        repo_name: ${{ inputs.repo-name }}
        owner_name: ${{ inputs.owner-name }}
      run: |
        gh api \
          --method GET \
          --include \
          --verbose \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$owner_name/$repo_name
