name: "Repository Get"
description: "Get the repository Details if they exist"

inputs:
 repo-name:
   description: "Name of the repository to attempt to get"
   required: true
 owner-name:
   description: "The repository owner"
   required: true
 pat-token:
  description: "The GitHub token to use. It must have enough privileges to make API calls"
  required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Repo Get API calls"
      id: repo_get_call
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.pat-token }}
        repo_name: ${{ inputs.repo-name }}
        owner_name: ${{ inputs.owner-name }}
      run: |
        node ${{ github.workspace }}/.github/actions/repo-check-create/create_repo.mjs